"
  CREATE TABLE "INTEGRACION"."ITZBGSP" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"BUSINESS_LINE" VARCHAR2(50), 
	"REQUEST" CLOB, 
	"RESPONSE" CLOB, 
	"CREATE_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"REQUEST_DATE" TIMESTAMP (6), 
	"RESPONSE_DATE" TIMESTAMP (6), 
	"OP_TYPE" VARCHAR2(100), 
	"STATUS" VARCHAR2(100), 
	 CONSTRAINT "PK_ITZBGSP" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPMENT"  ENABLE, 
	 CONSTRAINT "JSON_CHECK_REQ" CHECK (REQUEST IS JSON) ENABLE, 
	 CONSTRAINT "JSON_CHECK_RES" CHECK (RESPONSE IS JSON) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPMENT" 
 LOB ("REQUEST") STORE AS SECUREFILE (
  TABLESPACE "DEVELOPMENT" ENABLE STORAGE IN ROW CHUNK 32768
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 425984 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RESPONSE") STORE AS SECUREFILE (
  TABLESPACE "DEVELOPMENT" ENABLE STORAGE IN ROW CHUNK 32768
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 425984 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) "

---------------

"
  CREATE TABLE "INTEGRACION"."SZRSSBP" 
   (	"SZRSSBP_TERM_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"SZRSSBP_CRN" VARCHAR2(5 CHAR), 
	"SZRSSBP_PTRM_CODE" VARCHAR2(3 CHAR), 
	"SZRSSBP_SUBJ_CODE" VARCHAR2(4 CHAR), 
	"SZRSSBP_CRSE_NUMB" VARCHAR2(5 CHAR), 
	"SZRSSBP_PTRM_START_DATE" DATE, 
	"SZRSSBP_CRSE_TITLE" VARCHAR2(30 CHAR), 
	"SZRSSBP_MAX_ENRL" NUMBER(4,0), 
	"SZRSSBP_LINE_NEG" VARCHAR2(2), 
	"SZRSSBP_STATE" VARCHAR2(10), 
	"SZRSSBP_OPERACION" VARCHAR2(1), 
	"SZRSSBP_SURROGATE_ID" NUMBER(19,0), 
	"SZRSSBP_VERSION" NUMBER(19,0), 
	"SZRSSBP_DATA_ORIGIN" VARCHAR2(30 CHAR), 
	"SZRSSBP_USER_ID" VARCHAR2(30 CHAR), 
	"SZRSSBP_ACTIVITY_DATE" DATE, 
	"SZRSSBP_STATE_DET" VARCHAR2(200), 
	"SZRSSBP_ID_MAESTRO" NUMBER(19,0), 
	 CONSTRAINT "UK_SZRSSBP" UNIQUE ("SZRSSBP_TERM_CODE", "SZRSSBP_CRN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPMENT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPMENT" "

-------------

"
  CREATE TABLE "INTEGRACION"."SZRTMBP" 
   (	"SZRTMBP_TERM_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"SZRTMBP_PTRM_CODE" VARCHAR2(3 CHAR), 
	"SZRTMBP_DESC" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"SZRTMBP_START_DATE" DATE NOT NULL ENABLE, 
	"SZRTMBP_END_DATE" DATE NOT NULL ENABLE, 
	"SZRTMBP_LINE_NEG" VARCHAR2(2), 
	"SZRTMBP_STATE" VARCHAR2(10), 
	"SZRTMBP_OPERACION" VARCHAR2(1), 
	"SZRTMBP_SURROGATE_ID" NUMBER(19,0), 
	"SZRTMBP_VERSION" NUMBER(19,0), 
	"SZRTMBP_DATA_ORIGIN" VARCHAR2(30 CHAR), 
	"SZRTMBP_USER_ID" VARCHAR2(30 CHAR), 
	"SZRTMBP_ACTIVITY_DATE" DATE, 
	"SZRTMBP_ID_MAESTRO" NUMBER(19,0), 
	 CONSTRAINT "UK_SZRTMBP" UNIQUE ("SZRTMBP_TERM_CODE", "SZRTMBP_PTRM_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPMENT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPMENT" "

---

"
  CREATE TABLE "INTEGRACION"."ITZSUPL" 
   (	"ITZSUPL_TERM_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"ITZSUPL_PTRM_CODE" VARCHAR2(3 CHAR), 
	"ITZSUPL_CRN" VARCHAR2(5 CHAR), 
	"ITZSUPL_LINE_NEG" VARCHAR2(2), 
	"ITZSUPL_ID_MAESTRO" NUMBER(19,0), 
	"ITZSUPL_VALOR" VARCHAR2(10), 
	"ITZSUPL_SURROGATE_ID" NUMBER(19,0), 
	"ITZSUPL_VERSION" NUMBER(19,0), 
	"ITZSUPL_DATA_ORIGIN" VARCHAR2(30 CHAR), 
	"ITZSUPL_USER_ID" VARCHAR2(30 CHAR), 
	"ITZSUPL_ACTIVITY_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPMENT" "

