create or replace TRIGGER integracion.TRG_SZRTMBP_BI
BEFORE INSERT ON integracion.SZRTMBP
FOR EACH ROW
BEGIN
    IF :NEW.SZRTMBP_SURROGATE_ID IS NULL THEN
        SELECT SEQ_SZRTMBP.NEXTVAL
        INTO :NEW.SZRTMBP_SURROGATE_ID
        FROM DUAL;
    END IF;

    :NEW.SZRTMBP_ACTIVITY_DATE := SYSDATE;
END;
