
CREATE TABLE integracion.SZRPEBP (
    SZRPEBP_PIDM           NUMBER(8,0) NOT NULL,
	SZRPEBP_TERM_CODE	   VARCHAR2(6),
    SZRPEBP_LINE_NEG       VARCHAR2(2),
    SZRPEBP_ROL            VARCHAR2(20),
    SZRPEBP_STATE          VARCHAR2(10),
	SZRPEBP_OPERACION	   VARCHAR2(1),
	SZRPEBP_ID_MAESTRO	   NUMBER(19,0),
    SZRPEBP_SURROGATE_ID   NUMBER(19,0),
    SZRPEBP_VERSION        NUMBER(19,0),
    SZRPEBP_DATA_ORIGIN   VARCHAR2(30 CHAR),
    SZRPEBP_USER_ID        VARCHAR2(30 CHAR),
    SZRPEBP_ACTIVITY_DATE  DATE
);


COMMENT ON TABLE integracion.SZRPEBP IS 'INTEGRACION PERSONAS sistema Brightspace';
COMMENT ON COLUMN integracion.SZRPEBP.SZRPEBP_PIDM IS 'PIDIM PERSONA';
COMMENT ON COLUMN integracion.SZRPEBP.SZRPEBP_TERM_CODE IS 'PERIODO DEL DOCENTE';
COMMENT ON COLUMN integracion.SZRPEBP.SZRPEBP_LINE_NEG IS 'LINEA DE NEGOCIO (00 Online, 01 Flex, 03  CyP) ';
COMMENT ON COLUMN integracion.SZRPEBP.SZRPEBP_ROL IS 'ROL: DOCENTE ONLINE, DOCENTE ASISTENTE, ESTUDIANTE';
COMMENT ON COLUMN integracion.SZRPEBP.SZRPEBP_STATE IS 'ESTADO DEL REGISTRO (NEW -> BANNER)/(SEND -> TABLA INTEGRACION/ FAIL -> .NET/TABLA INT) ';
COMMENT ON COLUMN integracion.SZRPEBP.SZRPEBP_OPERACION IS 'OPERACION EFECTUADA EN EL REGISTRO ((I)nsert, (U)pdate, (D)elete) ';
COMMENT ON COLUMN integracion.SZRPEBP.SZRPEBP_ID_MAESTRO IS 'Identificador único de la tabla de integracion ITZBGSP.id ';
COMMENT ON COLUMN integracion.SZRPEBP.SZRPEBP_SURROGATE_ID IS 'Identificador único para cada registro ';
COMMENT ON COLUMN integracion.SZRPEBP.SZRPEBP_VERSION IS 'Versión del registro ';
COMMENT ON COLUMN integracion.SZRPEBP.SZRPEBP_DATA_ORIGIN IS ' Origen de datos';
COMMENT ON COLUMN integracion.SZRPEBP.SZRPEBP_USER_ID IS ' Usuario última modificación';
COMMENT ON COLUMN integracion.SZRPEBP.SZRPEBP_ACTIVITY_DATE IS 'Fecha de creación o actualización ';


CREATE SEQUENCE integracion.SEQ_SZRPEBP
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- ============================================
-- TRIGGER PARA SURROGATE_ID
-- ============================================

CREATE OR REPLACE TRIGGER TRG_SZRPEBP_BI
BEFORE INSERT ON integracion.SZRPEBP
FOR EACH ROW
BEGIN
    IF :NEW.SZRPEBP_SURROGATE_ID IS NULL THEN
        SELECT integracion.SEQ_SZRPEBP.NEXTVAL
        INTO :NEW.SZRPEBP_SURROGATE_ID
        FROM DUAL;
    END IF;

    :NEW.SZRPEBP_ACTIVITY_DATE := SYSDATE;
END;
/

GRANT SELECT, UPDATE, DELETE ON integracion.SZRPEBP TO PUBLIC;


CREATE PUBLIC SYNONYM SZRPEBP FOR integracion.SZRPEBP;