-- tabla de auditoría de la tabla SIRICNT 
CREATE TABLE PRGNREP.SZASIRI
(
    SZASIRI_PIDM              NUMBER(8,0)       NOT NULL,
    SZASIRI_TERM_CODE_EFF     VARCHAR2(6 CHAR)  NOT NULL,
    SZASIRI_FCNT_CODE         VARCHAR2(2 CHAR)  NOT NULL,
    SZASIRI_CNTR_CODE         VARCHAR2(6 CHAR)  NOT NULL,
    SZASIRI_DEF_IND           VARCHAR2(1 CHAR),
    SZASIRI_ACTIVITY_DATE     DATE,
    SZASIRI_SURROGATE_ID      NUMBER(19,0)      NOT NULL,
    SZASIRI_VERSION           NUMBER(19,0),
    SZASIRI_USER_ID           VARCHAR2(30 CHAR),
    SZASIRI_DATA_ORIGIN       VARCHAR2(30 CHAR),
    SZASIRI_VPDI_CODE         VARCHAR2(6 CHAR),
    SZASIRI_OPERATION         VARCHAR2(10 CHAR)
);

CREATE SEQUENCE PRGNREP.SZASIRI_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
	
CREATE OR REPLACE TRIGGER PRGNREP.TRG_SZASIRI_BI
BEFORE INSERT ON PRGNREP.SZASIRI
FOR EACH ROW
BEGIN
    IF :NEW.SZASIRI_SURROGATE_ID IS NULL THEN
        SELECT PRGNREP.SZASIRI_SEQ.NEXTVAL
          INTO :NEW.SZASIRI_SURROGATE_ID
          FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE PUBLIC SYNONYM SZASIRI FOR PRGNREP.SZASIRI;

GRANT SELECT, INSERT, UPDATE, DELETE ON PRGNREP.SZASIRI TO PUBLIC;