--PERIODO
grant execute on integracion.PKG_INT_BRIPACE_TERM to public

CREATE PUBLIC SYNONYM PKG_INT_BRIPACE_TERM FOR integracion.PKG_INT_BRIPACE_TERM;

GRANT SELECT, UPDATE, DELETE ON INTEGRACION.SZRTMBP TO PUBLIC;


CREATE PUBLIC SYNONYM SZRTMBP FOR integracion.SZRTMBP;

--NRC
grant execute on integracion.PKG_INT_BRIPACE_NRC to public

CREATE PUBLIC SYNONYM PKG_INT_BRIPACE_NRC FOR integracion.PKG_INT_BRIPACE_NRC;


grant execute on integracion.PKG_INT_BRIPACE_ENROLL to public;


CREATE PUBLIC SYNONYM PKG_INT_BRIPACE_ENROLL FOR integracion.PKG_INT_BRIPACE_ENROLL;

-- los errores


GRANT insert, SELECT, UPDATE, DELETE ON PRGNREP.SZRLGBP TO PUBLIC;


