CREATE TABLE PRGNREP.SZRLGBP (
    SZRLGBP_ID              NUMBER(19,0)     NOT NULL,
    SZRLGBP_BUSINESS_LINE   VARCHAR2(50 BYTE),
    SZRLGBP_OP_TYPE         VARCHAR2(100 BYTE),
    SZRLGBP_TERM_CODE       VARCHAR2(6 BYTE),
	SZRLGBP_PTRM_CODE       VARCHAR2(3 BYTE),
    SZRLGBP_CRN             VARCHAR2(5 BYTE),
    SZRLGBP_PIDM            NUMBER(8,0),
	SZRLGBP_ERROR_CODE      varchar2(50),
    SZRLGBP_ERROR_MESSAGE   VARCHAR2(4000 BYTE),
    SZRLGBP_ID_MAESTRO      NUMBER(19,0),
    SZRLGBP_STATE           VARCHAR2(30 BYTE),
    SZRLGBP_USER_ID         VARCHAR2(30 BYTE),
    SZRLGBP_ACTIVITY_DATE   DATE DEFAULT SYSDATE,
    SZRLGBP_DATA_ORIGIN     VARCHAR2(30 BYTE)
);


CREATE PUBLIC SYNONYM SZRLGBP FOR PRGNREP.SZRLGBP;

CREATE SEQUENCE PRGNREP.SEQ_SZRLGBP
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
    CREATE OR REPLACE TRIGGER PRGNREP.TRG_SZRLGBP_BI
BEFORE INSERT ON PRGNREP.SZRLGBP
FOR EACH ROW
BEGIN

    IF :NEW.SZRLGBP_ID IS NULL THEN
        :NEW.SZRLGBP_ID := PRGNREP.SEQ_SZRLGBP.NEXTVAL;
    END IF;

    IF :NEW.SZRLGBP_ACTIVITY_DATE IS NULL THEN
        :NEW.SZRLGBP_ACTIVITY_DATE := SYSDATE;
    END IF;

END;
/

COMMENT ON TABLE PRGNREP.SZRLGBP IS
'Log de errores de integracion con Brightspace';

COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_ID IS
'Identificador secuencial autogenerado del registro de error';

COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_BUSINESS_LINE IS
'Linea de negocio: ONLINE, FLEX o CYP';

COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_OP_TYPE IS
'Tipo de operacion: CREATE_TERM, UPD_TERM, CREATE_USER, UPD_USER, DEL_USUARIO, CREATE_NRC, UPD_NRC, ENROLLMENT_TEACHER, ENROLLMENT_STUDENT';

COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_ERROR_CODE IS
'Codigo del error Oracle';

COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_ERROR_MESSAGE IS
'Mensaje del error';


COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_TERM_CODE IS
'Codigo del periodo asociado al error';

COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_PTRM_CODE IS
'Codigo parte de periodo asociado al error';

COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_CRN IS
'CRN del curso asociado al error';

COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_PIDM IS
'PIDM de la persona asociada al error';

COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_ID_MAESTRO IS
'Identificador del registro maestro asociado al error';


COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_STATE IS
'Estado del error: NEW, RETRY o RESOLVED';

COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_USER_ID IS
'Usuario o proceso que genero el error';

COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_ACTIVITY_DATE IS
'Fecha y hora de registro del error';

COMMENT ON COLUMN PRGNREP.SZRLGBP.SZRLGBP_DATA_ORIGIN IS
'Origen de los datos o proceso que genero el error';