CREATE OR REPLACE TRIGGER integracion.TRG_SZREDBP_BI
BEFORE INSERT ON integracion.SZREDBP
FOR EACH ROW
BEGIN
    IF :NEW.SZREDBP_SURROGATE_ID IS NULL THEN
        SELECT integracion.SEQ_SZREDBP.NEXTVAL
          INTO :NEW.SZREDBP_SURROGATE_ID
          FROM DUAL;
    END IF;

    IF :NEW.SZREDBP_ACTIVITY_DATE IS NULL THEN
        :NEW.SZREDBP_ACTIVITY_DATE := SYSDATE;
    END IF;

    IF :NEW.SZREDBP_VERSION IS NULL THEN
        :NEW.SZREDBP_VERSION := 0;
    END IF;
END;
/